apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  PGDATA: /var/lib/postgresql/data/db-files/
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: obama